### ISSUE TITLE
New Shortcut Suggestion

### ISSUE THREAD

**Issue by chojicho** [Liresol/anki-custom-shortcuts#102]
Hi,
First of all, thank you for such an amazing add-on.

I thought that it might be very useful if there is a shortcut for mouse third/fourth buttons. For instance, the mouse third button could be used for "Good" and the fourth button for "Bad" on review cards. Not knowing the program that runs Anki, I am not sure if this is feasible. It seemed that it could be convenient for those who like working with mouse. 

Thank you,

**Comment by thiswillbeyourgithub** [comment]
You are looking for the addon "review hotmouse"

**Comment by chojicho** [comment]
I did not know about that addon!
Thank you for the information.
