### ISSUE TITLE
[Feature Request] Multiple shortcuts assigned to one function

### ISSUE THREAD

**Issue by Cardosaum** [Liresol/anki-custom-shortcuts#105]
Hi!

I'd like to be able to assign multiple shortcuts to the same function.

For example, pressing "3" or "k" to trigger "reviewer choice 3".

Would it be possible?

I tried to use a list instead of a single character in the config file but when restarting Anki I got a `TypeError: unhashable type: 'list'` error.

It's not a big deal though as I could use [other addon to this specific use case](https://ankiweb.net/shared/info/850294128)

Thanks for the attention and for this awesome addon! a really life-saver :)

**Comment by Liresol** [comment]
Hello,

This feature actually already exists to a degree. 

You can assign 2 shortcuts to the same function by adding the function-shortcut pair into the appropriate `_duplicates` object. For example, to have `3` and `k` trigger `reviewer choice 3` you could set `"reviewer choice 3": "3"` in the normal spot and add 
`"reviewer _duplicates": {"reviewer choice 3": "k"}`
using the `"reviewer _duplicates"` object. There are similar objects for the toolbar and editor, which let you duplicate shortcuts for those as well.

**Comment by Cardosaum** [comment]
Thanks! 

I should had read the `config.md` more closely 😆

**Comment by rikrdo89** [comment]
Is there any way to make the  `"reviewer _duplicates"` object accept repeated functions so we can bind multiple keys (more than 2) to a given function?
