### ISSUE TITLE
"Return" to reveal answer stops working when focus is on card area

### ISSUE THREAD

**Issue by glutanimate** [Liresol/anki-custom-shortcuts#11]
Hi there!

Thanks first of all for all of your work on this add-on! It's nice to finally have a generalized keyboard reassignment solution.

I stumbled on a small issue while working on [Refocus Card when Reviewing](https://ankiweb.net/shared/info/1642550423): It seems like, with Customize Keyboard Shortcuts installed, Return to reveal the answer only works if the bottom web area is focused. [I first thought that this was an issue with Refocus Cards](https://github.com/glutanimate/anki-addons-misc/issues/59#issuecomment-423138990), but it turned out to be a general issue with widget focus.

**Steps to reproduce**:

1. Click on the card area in the Reviewer
2. Hit the Return/Enter key

Expected result: answer revealed

Actual result: no action performed

Please let me know if you need any more info.

**Comment by omega3** [comment]
I can confirm that I also have this issue.

**Comment by omega3** [comment]
I have not done a very detailed testing of every Anki function with all add-on but  Refocus Card when Reviewing works as expected and your add-on that I use for F2 as edit also works. Thank you.

**Comment by glutanimate** [comment]
@Liresol Thanks for the lightning-fast response and update! Everything seems to be working perfectly now. Not sure about the non addon interaction test case, might have been platform-specific (I'm using Linux), but all is well now. Great job!
