### ISSUE TITLE
Numpad (numeric) Enter key doesn't work

### ISSUE THREAD

**Issue by Zupicz** [Liresol/anki-custom-shortcuts#111]
Hi!

I've set up the Add function to Ctrl+Enter, which works fine with regular Enter key, but not with the Numpad (numeric) Enter key.

`"main add": "Ctrl+Enter"`

How can I differentiate between the two Enter keys? I have tried KP_Enter and other nomenclatures to no avail. Having "Add" bind to Ctrl + numeric Enter would be much more convenient for me.

**Comment by Liresol** [comment]
Hello,

The numpad enter key should be `Qt.Key_Enter`, so using `"main add": "Ctrl+Qt.Key_Enter"` should work for triggering the add card window on the main page. Looking now I might want to simplify this in the future.

As a sidenote (and kind of my fault) this might not be the function you're looking for. In particular, if you're in the add card window and want to confirm adding the card, that's `"editor confirm add card"`, and creating triggering the add card window from the browser is  `"window_browser add note"`

Anyway, if changing the shortcut doesn't work, let me know and I will look into it further.

**Comment by Zupicz** [comment]
Whoops! You were right, I was trying to change a wrong function. 

Writing `"editor confirm add card": "Ctrl+Enter"` did the trick!

Thank you.

**Comment by Liresol** [comment]
No problem.
Closing the issue now, but if anything else comes up, don't hesitate to put up another issue.
