### ISSUE TITLE
When I change it the "editor cloze alt" option don't working.

### ISSUE THREAD

**Issue by jwdevelab** [Liresol/anki-custom-shortcuts#124]
As I said in the title, when I change, it just works like the "editor cloze" option.

**Comment by Liresol** [comment]
Hello,
Sorry for the confusion, but that functionality (insert a cloze but don't increment the cloze number) got moved to `editor cloze no increment`. If that doesn't work, just let me know and I will get back to you as soon as possible.

The reason why `editor cloze alt` and `editor cloze` are now the same is that the old way had bad interactions with other addons that modified how cloze worked. 
Hopefully this hasn't been too much of a hassle for you.

**Comment by jwdevelab** [comment]
That was a pretty fast response, thank you. It works excellent right now! I was using old Anki up to a week before and I have been so upset that I couldn't find a method to do that. Thank you, again.
