### ISSUE TITLE
Add support for sidebar shortcuts introduced in 2.1.45

### ISSUE THREAD

**Issue by x51mon** [Liresol/anki-custom-shortcuts#125]
With Anki version 2.1.45 shortcuts <kbd>Alt</kbd>+<kbd>1</kbd> and <kbd> Alt</kbd>+<kbd>2</kbd> were introduced for the sidebar in the browser.
[Description in the Anki manual](https://docs.ankiweb.net/browsing.html#sidebar)

I would like to disable those shortcuts.

**Comment by Liresol** [comment]
Hello,
I just pushed out an update for this, where the two shortcuts are `window_browser sidebar search` and  `window_browser sidebar select`. 
Setting those two shortcuts to `<nop>` should disable them.
If there are any issues, let me know and I will see what else I can do.

**Comment by x51mon** [comment]
Thank you, it works :)
