### ISSUE TITLE
Shortcut to change note type in editor (Add dialog) can't be changed

### ISSUE THREAD

**Issue by MarcelvC** [Liresol/anki-custom-shortcuts#128]
Setting a shortcut for "editor change note type" in the configuration seems to have no effect.

One clue might be that the default value of "editor change note type" is `"<nop>"` when in fact, there _is_ a default shortcut, namely "Ctrl+N".

Anki Version ⁨2.1.48 on Windows 10

**Comment by Liresol** [comment]
Hello,
I think the default value of this has actually always been Ctrl+N (and I missed it the first time I looked).
In any case, I have pushed out an update which should hopefully fix the shortcut functionality.
If there are any issues with the changes, just let me know and I will look into it further.

**Comment by MarcelvC** [comment]
Hi! I'm so sorry, this is more than a year late but I still wanted to let you know that it works flawlessly! Thanks for the fix and for a great add-on!
