### ISSUE TITLE
[feature request] shortcut for pasting special character in editor

### ISSUE THREAD

**Issue by omega3** [Liresol/anki-custom-shortcuts#13]
Can you please add a shortcut for pasting in editor a special character (html, css) predefined in add-on settings? Would be also great if user could add font size and color to it. It would be like pasting something like

`<span style="font-size: 20px; color:#3399ff">◆◆◆◆◆</span>`

I paste such characters to separate some parts of text to make it more legible.
https://i.imgur.com/04bTskT.png

The character could be from such list:
https://brajeshwar.github.io/entities/

It would be great if user could define like more than one such shortcut by multiplying the part of the code in add-on settings (in the same as it is possible to add shortcut for color in quick coloring add-on).

**Comment by Liresol** [comment]
I'm not sure that this feature request fits within the scope of this add-on, since it's asking for a completely new function instead of modifying existing ones.

I'll look into it, but it might be something worth creating a separate add-on.

**Comment by Liresol** [comment]
The feature has now been added, but is experimental since it's not originally in Anki.

The shortcut is set in "paste custom text" and the html text is set in "\u03a9 custom paste text".

The <span> tag worked in testing, so hopefully you can use the whole thing.

If there are any problems with it, feel free to bring up a new issue.

**Comment by Liresol** [comment]
The "paste custom text" is for the shortcut itself (e.g. it is mapped with lines like "paste custom text":"Ctrl+F3").

There is another field at the bottom labeled "\u03a9 custom paste text" where you can put the HTML, but you have to escape the quotes with backslashes like so:

"\u03a9 custom paste text": "<span style=\"font-size: 20px; color:#3399ff\">\u25c6\u25c6\u25c6\u25c6\u25c6</span>"

**Comment by omega3** [comment]
```
{
    "editor _extras": {
        "paste custom text": "Ctrl+7"
    },

```
and
```
    "\u03a9 custom paste text": "<span style=\"font-size: 20px; color:#ffaa00\">\u25c6\u25c6\u25c6\u25c6\u25c6</span>",
```

and it works perfectly. Thank you very much.

**Comment by omega3** [comment]
I have one issue with this add-on. It pastes custom text at the and of the filed, instead in the place where mouse pointer is. 
If you have like five lines and you want to paste custom text let's say between first and second it will jump to the end of field.

Can you check if you experience this, please.

Anki Version 2.1.4, Qt 5.9.2 PyQt 5.9 on Manjaro Linux Plasma 5.13.5, QT 5.11.1

**Comment by Liresol** [comment]
It's definitely something with the implementation of this add-on, though there is a very real chance that it's unsolvable (requires sacrificing either HTML preservation or in-position pasting).

**Comment by Liresol** [comment]
Used an approach that I didn't think would work (it worked), so the function should work better now.

**Comment by omega3** [comment]
It works correctly now. Thank you very much.
