### ISSUE TITLE
Shortcut for Sticky Fields with Anki 2.1.45+

### ISSUE THREAD

**Issue by Rekhyt370** [Liresol/anki-custom-shortcuts#144]
Hello,
with the update 2.1.45 the "Frozen Fields"-addon was implemented into Anki, with the default shortcut "F9". 
Could you add this shortcut to your addon, so that it is customizeable?

**Comment by Liresol** [comment]
Hello,
Sorry for the delay.
I've just pushed an update that adds this shortcut under `"editor toggle sticky current"` (as well as freezing/unfreezing all fields with `"editor toggle sticky all"`).
If there are any issues, let me know and I will look into it further.
