### ISSUE TITLE
How to create a shortcut for "increase indent" and "unordered list"

### ISSUE THREAD

**Issue by isaiah-a97** [Liresol/anki-custom-shortcuts#148]
I'm trying to a shortcut for both the "increase indent" button and also the "unordered list"  button using the "Customize Keyboard Shortcuts" add-on. How do I go about doing this, please?

**Comment by isaiah-a97** [comment]
Hi there, if anyone is able to create an update to add this feature urgently, that would be greatly appreciated. I don't even sending something via PayPal - but, please, I need it ASAP. Thanks.

**Comment by isaiah-a97** [comment]
Much love, mate!

**Comment by isaiah-a97** [comment]
Send me your PayPal pls

**Comment by Liresol** [comment]
Hello,
Thank you for the generous offer!
I want to emphasize that you're under no obligation to give anything and that I will most likely continue maintaining this addon even without monetary contributions.
Also I don't have any payment processors set up right now, so it might take a few days to figure things out before I could accept donations.
If you encounter anything else with this addon, just let me know and I'll see what I can do.
