### ISSUE TITLE
cannot find a shortcut to go to the previous card. 

### ISSUE THREAD

**Issue by yczhao7** [Liresol/anki-custom-shortcuts#149]
Hi, what I need is a one button shortcut that function as "ctrl + z". for example, when I already pass a card but suddenly wanted to go back to the card, what shortcut should i define to "undo" my last action? tysm!

**Comment by Liresol** [comment]
Hello,
The shortcut you are looking for to undo review actions is `"m_toolbox undo"`, which is set by default to `"Ctrl+Z"`. 
If you want it to just be set to a single button, an option I have seen before is setting it like `"m_toolbox undo": "Z"` which will undo when you press "Z". There are many other keys that should be available, so hopefully you can find one that you like.

**Comment by isaiah-a97** [comment]
Hi Liresol, any chance you could take a look at my issue pls. Thanks.
https://github.com/Liresol/anki-custom-shortcuts/issues/148

**Comment by Liresol** [comment]
Hello,
@isaiah-a97 
Please don't write in other issues in order to direct attention to your issue.
I'm going to close this issue since it sounds like things have been resolved here.
