### ISSUE TITLE
Error when trying to map new shortcuts

### ISSUE THREAD

**Issue by cherushton** [Liresol/anki-custom-shortcuts#152]
I bought an 8bitdo zero 2 to use for anki and it has been a massive hassle to get set up. I didn't realize you couldn't remap the buttons on the control, so I am forced to remap Anki. Luckily your addon lets me do that!

However, it keeps giving me an error with my current settings, and I don't know why. The error goes away when I disable the addon. Here is the error code it spits out:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-02-23 17:20:48

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 142, in _onCmd
  File "aqt\webview.py", line 595, in _onBridgeCmd
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\travi\AppData\Roaming\Anki2\addons21\review_heatmap\links.py", line 69, in heatmapLinkHandler
    return None if not _old else _old(self, url)
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\travi\AppData\Roaming\Anki2\addons21\563204849\__init__.py", line 139, in myLinkHandler
    return _old(self, url)
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 84, in repl
  File "aqt\overview.py", line 91, in _linkHandler
  File "aqt\main.py", line 672, in moveToState
  File "aqt\main.py", line 694, in _reviewState
  File "aqt\reviewer.py", line 135, in show
  File "aqt\main.py", line 1043, in setStateShortcuts
  File "aqt\main.py", line 1034, in applyShortcuts
TypeError: argument 1 has unexpected type 'NoneType'

**Comment by Liresol** [comment]
Hello,
I'm not actually sure how this error shows up due to the way that things are handled in Anki code.
Can you post which shortcuts you have changed and possibly what other addons you have?

**Comment by cherushton** [comment]
Yeah! I'll just go ahead and copy and paste in the config from the addon, so you can see it all. The only edits I added were to include extra additional inputs for 1/2/3/4 as well as undo and flip card. So I can use the controller for everything.
I also unfortunately had to change a couple other inputs because they were already assigned the same letter the controller inputs (I really wish I could just remap the dumb controller). Those were "more options" (M) and card info (I)
But anyways, here's the config:


{
    "editor _duplicates": {},
    "editor _extras": {
        "paste custom text": "<nop>"
    },
    "editor _pastes": {},
    "editor add card close window": "<default>",
    "editor add media": "F3",
    "editor block indent": "<nop>",
    "editor block outdent": "<nop>",
    "editor bold": "Ctrl+B",
    "editor card layout": "Ctrl+L",
    "editor change col": "F8",
    "editor change deck": "<nop>",
    "editor change note type": "Ctrl+N",
    "editor cloze": "Ctrl+Shift+C",
    "editor cloze alt": "Ctrl+Shift+Alt+C",
    "editor cloze forced increment": "<nop>",
    "editor cloze no increment": "<nop>",
    "editor confirm add card": "Ctrl+Return",
    "editor focus tags": "Ctrl+Shift+T",
    "editor foreground": "F7",
    "editor html edit": "Ctrl+Shift+X",
    "editor insert latex": "Ctrl+T, T",
    "editor insert latex equation": "Ctrl+T, E",
    "editor insert latex math environment": "Ctrl+T, M",
    "editor insert mathjax block": "Ctrl+M, E",
    "editor insert mathjax chemistry": "Ctrl+M, C",
    "editor insert mathjax inline": "Ctrl+M, M",
    "editor italic": "Ctrl+I",
    "editor list insert ordered": "<nop>",
    "editor list insert unordered": "<nop>",
    "editor record sound": "F5",
    "editor remove format": "Ctrl+R",
    "editor subscript": "Ctrl+=",
    "editor superscript": "Ctrl++",
    "editor toggle sticky all": "Shift+F9",
    "editor toggle sticky current": "F9",
    "editor underline": "Ctrl+U",
    "m_toolbox _duplicates": {},
    "m_toolbox addons": "Ctrl+Shift+A",
    "m_toolbox create filtered deck": "F",
    "m_toolbox export": "Ctrl+E",
    "m_toolbox import": "Ctrl+Shift+I",
    "m_toolbox preferences": "Ctrl+P",
    "m_toolbox quit": "Ctrl+Q",
    "m_toolbox see documentation": "F1",
    "m_toolbox study": "/",
    "m_toolbox switch profile": "Ctrl+Shift+P",
    "m_toolbox undo": "Ctrl+Z",
    "main add": "A",
    "main browse": "B",
    "main debug": "Ctrl+:",
    "main deckbrowser": "D",
    "main stats": "T",
    "main study": "S",
    "main sync": "Y",
    "reviewer _duplicates": {
        "m_toolbox undo": "m",
        "reviewer choice 1": "i",
        "reviewer choice 2": "h",
        "reviewer choice 3": "g",
        "reviewer choice 4": "j",
        "reviewer flip card 1": "k"
    },
    "reviewer bury card": "-",
    "reviewer bury note": "=",
    "reviewer card info": "F4",
    "reviewer choice 1": "1",
    "reviewer choice 2": "2",
    "reviewer choice 3": "3",
    "reviewer choice 4": "4",
    "reviewer delete note": "Ctrl+Delete",
    "reviewer edit current": "E",
    "reviewer flip card 1": " ",
    "reviewer flip card 2": "Qt.Key_Return",
    "reviewer flip card 3": "Qt.Key_Enter",
    "reviewer mark card": "*",
    "reviewer more options": "F3",
    "reviewer options menu": "o",
    "reviewer pause audio": "5",
    "reviewer play recorded voice": "v",
    "reviewer previous card info": "Alt+I",
    "reviewer record voice": "Shift+v",
    "reviewer replay audio 1": "r",
    "reviewer replay audio 2": "F5",
    "reviewer seek backward": "6",
    "reviewer seek forward": "7",
    "reviewer set due date": "Ctrl+Shift+D",
    "reviewer set flag 0": "Ctrl+0",
    "reviewer set flag 1": "Ctrl+1",
    "reviewer set flag 2": "Ctrl+2",
    "reviewer set flag 3": "Ctrl+3",
    "reviewer set flag 4": "Ctrl+4",
    "reviewer suspend card": "@",
    "reviewer suspend note": "!",
    "window_browser _filters": {
        "_concat": {},
        "_orConcat": {}
    },
    "window_browser add note": "Ctrl+E",
    "window_browser add tag": "Ctrl+Shift+A",
    "window_browser change deck": "Ctrl+D",
    "window_browser change note type": "Ctrl+Shift+M",
    "window_browser clear unused tags": "<nop>",
    "window_browser close": "Ctrl+W",
    "window_browser delete": "Ctrl+Del",
    "window_browser filter": "Ctrl+Shift+F",
    "window_browser find": "Ctrl+F",
    "window_browser find and replace": "Ctrl+Alt+F",
    "window_browser find duplicates": "<nop>",
    "window_browser first card": "Home",
    "window_browser flag_blue": "Ctrl+4",
    "window_browser flag_green": "Ctrl+3",
    "window_browser flag_orange": "Ctrl+2",
    "window_browser flag_red": "Ctrl+1",
    "window_browser goto card list": "Ctrl+Shift+L",
    "window_browser goto next note": "Ctrl+N",
    "window_browser goto note": "Ctrl+Shift+N",
    "window_browser goto previous note": "Ctrl+P",
    "window_browser goto sidebar": "Ctrl+Shift+R",
    "window_browser guide": "F1",
    "window_browser info": "Ctrl+Shift+I",
    "window_browser invert selection": "Ctrl+Alt+S",
    "window_browser last card": "End",
    "window_browser manage note types": "<nop>",
    "window_browser preview": "Ctrl+Shift+P",
    "window_browser remove current filter": "<nop>",
    "window_browser remove tag": "Ctrl+Alt+Shift+A",
    "window_browser reposition": "Ctrl+Shift+S",
    "window_browser reschedule": "Ctrl+Shift+D",
    "window_browser save current filter": "<nop>",
    "window_browser select all": "Ctrl+Alt+A",
    "window_browser select notes": "<nop>",
    "window_browser sidebar search": "Alt+1",
    "window_browser sidebar select": "Alt+2",
    "window_browser suspend": "Ctrl+J",
    "window_browser toggle mark": "Ctrl+K",
    "window_browser undo": "Ctrl+Alt+Z",
    "Ω custom paste end style": "n",
    "Ω custom paste extra texts": {},
    "Ω custom paste text": "",
    "Ω enable conflict warning": "y",
    "Ω enable editor": "y",
    "Ω enable m_toolbox": "y",
    "Ω enable main": "y",
    "Ω enable reviewer": "y",
    "Ω enable window_browser": "y"
}

**Comment by cherushton** [comment]
I've noticed that my undo shortcut has been changed to ctrl z. According to google this is normal. But mine was also JUST z, no ctrl. I can't seem to find an addon in my list that would've done this but I don't know why it was different all this time and now is not. Perhaps there's something I'm missing that has caused this issue and it is related to the change in my undo hotkey from ctrl z to z

**Comment by Liresol** [comment]
Hello,
The issue is most likely that you have `"m_toolbox undo": "m"` in `reviewer _duplicates` instead of `m_toolbox _duplicates`. 
Hopefully moving that to its corresponding location should fix the error.
Also, the default on this addon has the undo set to Ctrl+Z, so it's probably this addon that's doing that setting (setting `"m_toolbox undo": "Z"` somewhere will probably do the right thing).
If the issue still persists after moving the shortcuts around, let me know and I will try to look into it further.

**Comment by cherushton** [comment]
That fixed it! As soon as you pointed it out it became such an obvious error, but clearly I didn't recognize it before lol.
Thanks for your help
