### ISSUE TITLE
Preview button issue in browser tab

### ISSUE THREAD

**Issue by Frkn46** [Liresol/anki-custom-shortcuts#157]
The preview button in the browser tab disappears when you activate the plugin. It can work with hotkey.
Anki Current version 2.1.50 beta 6

![image](https://user-images.githubusercontent.com/101407113/159164285-762739cc-4056-48e1-a9dd-0bca6c627aa7.png)

**Comment by Liresol** [comment]
Hello,
Sorry for the delay in getting around to this.
I have just pushed out an update which should fix this issue.
If you still can't see the preview button in 2.1.50, let me know and I will look into it further.

**Comment by Frkn46** [comment]
Thanks. The update fixed the problem.
