### ISSUE TITLE
Will the browser shortcuts be added? That would be cool!

### ISSUE THREAD

**Issue by FiniTea** [Liresol/anki-custom-shortcuts#17]

**Comment by cabe7** [comment]
I second this. Browser shortcuts would be great!

**Comment by Liresol** [comment]
This last week was chaos for me, but I think can get the documentation written and have testing done by Tuesday.

**Comment by Liresol** [comment]
Added the features and pushed them to Anki. The new shortcuts can be customized under the prefix "window_browser".

If you encounter any problems with the new features (hopefully not), please report it with a new issue.
