### ISSUE TITLE
Can a custom shortcut be created for “card action: forget”？

### ISSUE THREAD

**Issue by dcwtt** [Liresol/anki-custom-shortcuts#170]
The default shortcut for the "card action: forget" in the browser is "ctrl+alt+n"，can it be changed？
And is it possible to forget a card in reviewer by shortcut？

**Comment by Liresol** [comment]
Hello,
I've just pushed out an update to enable changing this using the name `window_browser forget card`.
Once you update the addon, you should be able to change this.
If it doesn't work, let me know and I will look into it further.

**Comment by dcwtt** [comment]
It's working now，thanks a lot!

**Comment by akavi1** [comment]
Can we do this in the reviewer? The current shortcut customization only works in the browser. I tested this and it works:

`self.forget_current_card : [config_scuts["reviewer forget card"]]
`

https://github.com/Liresol/anki-custom-shortcuts/issues/194#issue-1494937787
