### ISSUE TITLE
CLOZE ADDS 2 WHEN I SUDE KEYBOARD SHORTCUT

### ISSUE THREAD

**Issue by mjq22flower** [Liresol/anki-custom-shortcuts#171]
90% of the time when I click shift + command + C it adds 2 cloze's even though there's nothing in the second cloze. I've added a picture to better explain what I mean. I dont know how to fix it and it doesn't happen every time... I thought maybe it was because I was pressing the key's too long or something and I tried pressing the keys as quick as I can but that didn't fix it either

<img width="1031" alt="Screen Shot 2022-06-28 at 3 32 11 PM" src="https://user-images.githubusercontent.com/108430517/176520979-898e7d9e-85ff-4b2a-9735-5c1139a507ad.png">

**Comment by joostin81** [comment]
Just tried updating to Anki 2.1.54 today and the same thing happened to me, no matter how I custom configured the shortcuts. So I had to downgrade back to 2.1.49. Bummer.

**Comment by mjq22flower** [comment]
ok yes just tried that it seemed to solve the issue
