### ISSUE TITLE
1) Can you add the Alt, Ctrl, Shift, and Fn keys as keybinding options?

### ISSUE THREAD

**Issue by AkashJ7** [Liresol/anki-custom-shortcuts#178]
Version: 2.1.54 Qt5
OS: Windows 11

1) I like this addon, but was interested in having the alt, shift, ctrl, and fn keys implemented as individually pressable buttons as well. But I also don't know what the Qt.Key_Alt/Fn codes would be, so if you have those or just make it so that "Fn" and "Alt" would work, that would be great. 

Here are the Qt codes/values or whatever since I noticed that some of the other ones also used this. There's no Fn/Function key :(. It would be fine if you couldn't do Fn.
![image](https://user-images.githubusercontent.com/24302856/178618504-0ffbb54e-fbaa-457d-b25d-0f6393e34df8.png)

**Comment by Liresol** [comment]
Hello,
Sorry for the inconvenience, but this probably isn't possible based on the framework that Anki uses. 
If the base shortcut component (QShortcut) in Qt doesn't support just Alt/Ctrl/Shift/Fn (i.e. you can't already use this setting), then it will be prohibitively difficult to implement it in an addon.
