### ISSUE TITLE
Reschedule shortcut not working

### ISSUE THREAD

**Issue by docdd6** [Liresol/anki-custom-shortcuts#179]
I updated my Anki to 2.1.54 Qt6.
Some of the assigned shortcuts are not working since the update.
For example; the default shortcut for Reschedule is Ctrl+Shift+D, I had it changed to Capslock.
It’s not working now. I even tried to change the shortcut key but still not working.

**Comment by Liresol** [comment]
Hello,
For the future, please do not call attention to existing issues by opening identical new issues. A comment on the initial issue will probably be enough to get my attention if I have the time to work on it.
Sorry for the inconvenience.

**Comment by docdd6** [comment]
Alright. Thank you.
