### ISSUE TITLE
2.1.54 Reviewer duplicats problem

### ISSUE THREAD

**Issue by MacAnMheiriceanaigh** [Liresol/anki-custom-shortcuts#183]
Hello,
Yesterday mid-day suddenly my most crucial custom shortcuts stopped working (all others are still working, and it's not a keyboard problem or anything)
Here is the section I added that was working until yesterday:

    "reviewer _duplicates": {
        "reviewer choice 1": "Qt.Key_PageDown",
        "reviewer flip card 1": "Qt.Key_PageUp"
    },

I use this so that I can use a PowerPoint clicker to do flashcards. I have suddenly lost that ability :( 
Any ideas on what I can do?
Thanks,
q

**Comment by Liresol** [comment]
Hello,
Nothing has changed recently for this addon, so I'm not sure what could have happened to have caused this. 
Have you recently updated Anki? If so, which version are you using and which one did you upgrade from?

**Comment by MacAnMheiriceanaigh** [comment]
Hello,
I am using 2.1.54 and before was also using 2.1.54. I reinstalled Anki thinking it might solve the problem but didn't. I can't be sure it was this add-on, as I have another one also, but one or both of the add-ons updated when the problem started. The other add-on is Awesome TTS.

**Comment by MacAnMheiriceanaigh** [comment]
Hello -
I apologize - I was able to identify the cause of the problem and it ended up not being with this add-on. Thank you so much for this excellent tool that is so crucial to my life :)
