### ISSUE TITLE
[bug] Editor cloze alt

### ISSUE THREAD

**Issue by shadoknaute** [Liresol/anki-custom-shortcuts#24]
Hello,

Everything works fine for me (anki 2.1.5), except one feature : the shortcut for "editor cloze alt". 

Everytime I change the shortcut to anything else than the default one (Ctrl+Shift+Alt+C), it works exactly like "editor cloze" by increamenting the number, instead of staying to the same number.
The only shortcut working for this feature is the default one   ##(Ctrl+Shift+Alt+C).

Thank you for your work :)

**Comment by Liresol** [comment]
Just pushed an update that (hopefully) fixes it. I'm going to leave the issue open for a few days in case there are bugs, since this update also makes some other significant changes.

**Comment by shadoknaute** [comment]
Works perfectly since your last updat, thanks a lot !

**Comment by thiswillbeyourgithub** [comment]
I am using the latest version of your addon on Anki 2.1.15 and the problem is here.

**Comment by Liresol** [comment]
Hello,
I can't seem to reproduce the bug with the latest version on Anki 2.1.15 on my machine.
Can you tell me the steps you took to produce the bug, the intended behavior, and what actually happened?
I will continue investigating, but this is quite an old bug, so it is somewhat surprising to see.

**Comment by thiswillbeyourgithub** [comment]
I will try to add some details in a comment in a few days, in the meantime : is it normal that changing the cloze shortcuts is actually only valid in the "add card" window and not in the browser when editing cards ?

**Comment by Liresol** [comment]
Shortcut changes only take effect after restarting Anki, but except for unusual edge cases, shortcut changes should persist in the card editing window as well.

As an aside, this probably doesn't affect you, but the cloze alt description was slightly inaccurate and has been changed to better reflect what it actually does.
