### ISSUE TITLE
"Undo review" mapped to ctrl+alt+z ?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [Liresol/anki-custom-shortcuts#29]
Hi,

I am on ubuntu 18 and installed your addon recently, but it seems to cause the undo review "ctrl+z" to be remapped to "ctrl+alt+z".

Is there a way to remap it to ctrl+z ? I don't see it in the config.

Thanks !

**Comment by Liresol** [comment]
The shortcut you are looking for is probably "m_toolbox undo", which I thought defaulted to Ctrl+Alt+Z in Anki 2.1 (but was Ctrl+Z in Anki 2.0). Anyway, remapping it with `"m_toolbox undo":"Ctrl+Z"` should fix the problem. If not, we can continue the issue from there.

Hope this helps.

**Comment by thiswillbeyourgithub** [comment]
Indeed it resolved the issue. Thanks for the quick help :) !

(personnaly, I think the the addon should leave ctrl+z as the default to avoid confusing people)
