### ISSUE TITLE
Answer with arrow keys

### ISSUE THREAD

**Issue by Najrim** [Liresol/anki-custom-shortcuts#30]
Why doesn't this work? Pressing the arrow keys when reviewing does nothing. I took the names of the keys from <https://doc.qt.io/archives/qtjambi-4.5.2_01/com/trolltech/qt/core/Qt.Key.html>

```
    "reviewer _duplicates": {
        "reviewer choice 1": "Qt.Key_Left",
        "reviewer choice 2": "Qt.Key_Down",
        "reviewer choice 3": "Qt.Key_Right",
        "reviewer choice 4": "Qt.Key_Up"
    },
```

**Comment by Liresol** [comment]
I think that's because I didn't actually implement functionality of those particular buttons. Once AnkiWeb finishes maintenance, I will push the update to add them.

**Comment by Najrim** [comment]
Thanks! I'll also take the opportunity to request `Key_PageUp` and `Key_PageDown` then :grin:

**Comment by Liresol** [comment]
Done. Hopefully that covers everything for now.
