### ISSUE TITLE
The addon changes language of the main window toolbar.

### ISSUE THREAD

**Issue by mjuzikfrik** [Liresol/anki-custom-shortcuts#31]
I have UI language in Anki set to Japanese bu with this addon the main window toolbar changes to English.
![screenshot_1](https://user-images.githubusercontent.com/16630872/53941952-cf25d000-40b9-11e9-86d8-82b45eafc6f1.png)

**Comment by Liresol** [comment]
I actually was expecting this bug to appear on my system, but for some reason it's not.

Could you provide more information about the version/OS you are using?

**Comment by mjuzikfrik** [comment]
Weird, it's working as expected now, tough it didn't yesterday. Sorry for the false alarm.

**Comment by Liresol** [comment]
I'm going to close the issue now, but if this bug resurfaces, comment here and I'll reopen it so we can figure it out.
