### ISSUE TITLE
Error when mapping undo

### ISSUE THREAD

**Issue by wushugirl05** [Liresol/anki-custom-shortcuts#32]
I have an error when changing undo from "Ctrl+Z" to "z." This was my code
`"window_browser undo": "z",`

I also tried remapping back to what it was before to "Ctrl+Z." This was my code
`"window_browser undo": "Ctrl+Z",`

OS: Windows
Anki version: 2.11 standard

**Comment by Liresol** [comment]
Do you happen to have the error message that it shows? I'm having trouble pinpointing where the bug occurs.

**Comment by wushugirl05** [comment]
Unfortunately, I do not have an error message. It just reverts back to the original shortcut which is Ctrl+Alt+Z

**Comment by Liresol** [comment]
The default shortcut for `"window_browser undo"` is `"Ctrl+Z"`, so something pretty weird is going on. Does the config reset instantly, or does it reset whenever you restart?
Also, just in case, update the addon just to make sure that this issue is in the current version.

**Comment by wushugirl05** [comment]
I just updated the addon, restarted it, and tried to use `"Ctrl+Z."` I did not alter `"window_browser undo"` mapping. It doesn't work. Weirdly enough, when I altered `"reviewer_choice"`, it worked.

**Comment by Liresol** [comment]
This might be a really dumb question, but are you trying to undo actions while reviewing cards (e.g. undo to correct an "Again" to "Good") or actions in the browser window (i.e. stuff done in "Browse")?

For some reason, Anki treats these two undos differently. Undoing on the browser window is the one handled by `"window_browser undo"`, while undoing while reviewing cards is under a different shortcut, named `"m_toolbox undo"` (it's a toolbar shortcut).

It's pretty much my fault for not describing these two shortcuts better, but we might accidentally be chasing the wrong shortcut.

**Comment by wushugirl05** [comment]
Thank you so much for bearing with me. I was trying to undo actions when reviewing cards, and I didn't realize that Anki treats "undos" differently. My problem is solved now

**Comment by Liresol** [comment]
I've changed the config file to mention the differences between the two undos so that hopefully this confusion won't happen in the future. I'm also going to close the issue now, but don't hesitate to bring up any new issues or feature requests.
