### ISSUE TITLE
Not clear how to use duplicate

### ISSUE THREAD

**Issue by nicktohzyu** [Liresol/anki-custom-shortcuts#36]
The description for "m_toolbox _duplicates" is pretty confusing, can you please provide an example of how I can duplicate "reviewer suspend card" to both "@" and "+"

**Comment by Liresol** [comment]
Shortcut duplicates are grouped into their own categories and act like their own mini-version of the larger config file. The duplications for reviewer shortcuts is stored in `"reviewer _duplicates"`, and duplicating `"reviewer suspend card"` to `@` and `+` would involve:

Setting `"reviewer suspend card"` to `@` (which it is by default),

and adding the other binding to the `"reviewer _duplicates"` object, like so:

`"reviewer _duplicates": {
	"reviewer suspend card": "+"
}`

The full example file can be seen here (only the `"reviewer _duplicates"` line is changed from default):
https://pastebin.com/WWcD6v7m

**Comment by Liresol** [comment]
Hello again,
If there aren't any further questions, I'll close this issue when it reaches 2 weeks old.
