### ISSUE TITLE
[feature request] F2 for edit

### ISSUE THREAD

**Issue by omega3** [Liresol/anki-custom-shortcuts#4]
Can you please add this shortcut: F2 for edit?

In Anki 2.0 I used a diffrent add-on for this but it was abandoned. 
https://anki.tenderapp.com/discussions/add-ons/18912-f4-edit-addon-please-update-to-anki-21

Is it possible to disable some of the shortcuts in your add-on when I don't use it?

**Comment by Liresol** [comment]
Reviewer customization has been added (and should work). To set F2 to edit, change the line
"reviewer edit current":"e" to 
"reviewer edit current":"F2".
Disabling shortcuts can be done by changing them to invalid options like `<nop>`.
