### ISSUE TITLE
How do i use arrow keys?

### ISSUE THREAD

**Issue by muneebhussain15** [Liresol/anki-custom-shortcuts#43]
I want to use arrow keys instead of 
1, 2, 3, 4 as review keys

**Comment by Liresol** [comment]
Arrow keys are represented by their Qt-Keyboard name, so for example the left arrow is "Qt.Key_Left" and the up arrow is "Qt.Key_Up".

Other than that, setting them as shortcuts is exactly the same as any other key.

**Comment by muneebhussain15** [comment]
Thank you so much
