### ISSUE TITLE
Formatting in doc: markdown needs a space:

### ISSUE THREAD

**Issue by aquarial** [Liresol/anki-custom-shortcuts#46]
The markdown headers in https://github.com/Liresol/anki-custom-shortcuts/blob/master/custom_shortcuts/config.md are slightly misconfigured. GitHub brand markdown may be more strict about the space than other versions.

## source

```markdown
#####header no space

##### header space
```
## result

#####header no space

##### header space

**Comment by Liresol** [comment]
This took embarrassingly long for anyone to raise any questions about.
The appropriate changes have (hopefully) been made.

**Comment by aquarial** [comment]
Nice.
