### ISSUE TITLE
Can't change keys on mac

### ISSUE THREAD

**Issue by balanjoop** [Liresol/anki-custom-shortcuts#48]
I'm unable to change the mapped keys to anything else. Even though I change the code, it still only works for the keys that are assigned as the default. In particular, I'm trying to change:

    "reviewer choice 1": "j",
    "reviewer choice 2": "k",
    "reviewer choice 3": "l",
    "reviewer choice 4": ";"

    "m_toolbox undo": "z"

**Comment by Liresol** [comment]
It is certainly probable that there is a bug involved, but just to make sure, configs do not take effect until Anki is restarted, and this might just be a side effect of that.
In the likelihood that the issue persists or behavior is still not expected, please comment anything you find and I will investigate further.

**Comment by balanjoop** [comment]
I ended up reinstalling Anki and that did the trick! Thanks for your help!

**Comment by Liresol** [comment]
Good to know that the issue was not a significant bug.
For future reference, shortcut changes take effect after closing Anki and opening it again, so hopefully you don't have to go through this again.
