### ISSUE TITLE
Updated to Anki 2.1.21, add-on "not supported"

### ISSUE THREAD

**Issue by PayDayBaby** [Liresol/anki-custom-shortcuts#61]
Just updated to 2.1.21, and I updated to your latest add-on version. When the add-on is disabled, Anki opens successfully. When the custom shortcuts add-on is enabled, I get these error messages and am unable to open Anki. After these messages, it prompts me to select a profile, then it shows the "Anki was unable to open your collection file" error message again. It does the same if I select a back-up. Any advice?

![image](https://user-images.githubusercontent.com/61957643/76181520-9f068680-617e-11ea-8837-7b046c2abb42.png)

**Comment by Liresol** [comment]
2.1.21 was released really recently (within the last couple of hours?) and the most recent update was tested with the pre-release betas, so I'll try to figure this one out as soon as possible.

**Comment by Liresol** [comment]
Just pushed out an update for 2.1.21 release. Hopefully it should work now, but if it doesn't, just report back and I will look into it further.

**Comment by PayDayBaby** [comment]
Works now! Thank you for the quick fix!

**Comment by Liresol** [comment]
Alright, good to know. 
I'm closing the issue for now, but if there are any problems in the future, just report them and I will do my best to fix them.
