### ISSUE TITLE
[Feature Suggestion] Add Additional Custom Paste Texts

### ISSUE THREAD

**Issue by schmidhauser** [Liresol/anki-custom-shortcuts#63]
I think it could be very useful if one could specify more than one custom text – for instance:

```json
"editor _extras": {
	"paste custom 01": "Meta+Ctrl+Shift+Alt+1",
	"paste custom 02": "Meta+Ctrl+Shift+Alt+2",
},

"Ω custom paste 01": "<p>.</p>",
"Ω custom paste 02": "<blockquote>.</blockquote>",
```

**Comment by Liresol** [comment]
Just pushed out an update for this.

The feature was added under `editor _pastes` (adding stuff to `editor _extras` either behaved badly or wasn't very backwards compatible, though the meaning of "extras" is now a little off)

`editor _pastes` controls the shortcuts for any given text, which you can label with anything.

The text pasted is controlled by `Ω custom paste extra texts`, which controls what text each label pastes.

e.g. 
`"editor _pastes": {"dashes":"Ctrl+Shift+5", "dots":"Ctrl+Shift+6"}` and 
`"Ω custom paste extra texts": {"dashes":"<b>--</b>","dots":". . ."}` pastes bolded dashes with `Ctrl+Shift+5` and spaced dots with `Ctrl+Shift+6`.

**Comment by schmidhauser** [comment]
Great.
