### ISSUE TITLE
Undo while reviewing, multiple shortcuts for undo

### ISSUE THREAD

**Issue by bradydjohnson** [Liresol/anki-custom-shortcuts#66]
I am using Karabiner-Elements to remap a key (f19) on a controller to perform an undo/go back function while reviewing. 

1) What is the function that does Undo/go back while reviewing?
2) Is it possible to map this function to multiple shortcuts (ideally Ctrl+Z and another shortcut)? It seems like the reviewer_duplicates may only work for reviewer commands, and neither of these start with 'reviewer.'
    "m_toolbox undo": "Ctrl+Z",
    "window_browser undo": "Ctrl+Z",

I've tried variation of the following with no success, too
    "window_browser undo": ["Ctrl+Z", ";"],

**Comment by bradydjohnson** [comment]
Customize Keyboard Shortcuts:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/6741590/79029113-8bbd5100-7b58-11ea-8bc9-fe2d9b4bb853.png">

Karabiner-Elements:
<img width="993" alt="image" src="https://user-images.githubusercontent.com/6741590/79029129-9b3c9a00-7b58-11ea-8984-34a7a70e35b1.png">
<img width="495" alt="image" src="https://user-images.githubusercontent.com/6741590/79029142-b0b1c400-7b58-11ea-823f-c6ea78eae765.png">

**Comment by Liresol** [comment]
For reviewing, the shortcut is `"m_toolbox undo"`. The reason it is not `reviewer undo` is that the function is not coded as part of the reviewer, with the main side effect being that you can also undo from the main window. The naming is pretty confusing (and there is a completely separate undo function elsewhere that makes matters worse), so I will likely try to make this clearer in the `config.md` in the future.

`m_toolbox` also has duplicate functionality, so you can use `"m_toolbox undo": "Ctrl+Z"` along with `    "m_toolbox _duplicates": {
        "m_toolbox undo": "Z"
    }` to get both shortcuts working.

**Comment by bradydjohnson** [comment]
Thank you! This seems to work.
