### ISSUE TITLE
Problem with reviewer _duplicates

### ISSUE THREAD

**Issue by Enenke** [Liresol/anki-custom-shortcuts#67]
Hello there. I first wanna say thanks for the awesome add-on. 
So basically the problem is when i try to set "reviewer _duplicates" to this:
"reviewer choice 1":"j","reviewer choice 2":"k","reviewer choice 3":"l", "reviewer choice 4":";"
It ends up replacing the normal choices. I am looking to use 1,2,3,4 as well as j,k,l,; but whenever I set that in duplicates, it overrides the normal 1,2,3,4 so only jkl; works. Is there a way to have both 1234 and jkl; work at the same time? I assumed this way would work from the comments, but I think I'm doing something wrong or there's a glitch or something. Help would be much appreciated.

**Comment by Liresol** [comment]
Hello,

That's a pretty weird behavior that I can't reproduce right now. If the regular `reviewer choice` values are still 1,2,3,4, they should still work as intended with the duplicate keys. If you close and reopen the config window again, it will reformat and display what it interprets all the shortcuts to be, which might be slightly different from your input. If nothing seems off (maybe you might want to copy-paste relevant parts), then just report back here and I will investigate further.

**Comment by Enenke** [comment]
This is what I have currently:
"reviewer _duplicates": {
        "reviewer choice 1": "j",
        "reviewer choice 2": "k",
        "reviewer choice 3": "l",
        "reviewer choice 4": ";"
    },
    "reviewer bury card": "-",
    "reviewer bury note": "=",
    "reviewer choice 1": "1",
    "reviewer choice 2": "2",
    "reviewer choice 3": "3",
    "reviewer choice 4": "4",
