### ISSUE TITLE
[Feature suggestion] Editor duplicates

### ISSUE THREAD

**Issue by muyiwafly** [Liresol/anki-custom-shortcuts#72]
Thanks for the wonderful add-on.

Is it possible to add an editor duplication feature similar to the reviewer duplicator feature? I do not see "editor _duplicates": { }, within the configuration options.

**Comment by Liresol** [comment]
Sorry for the delay,
I have just pushed out an update for this.
If there are any issues with the new feature, just put them here and I will try to get to them as soon as I can.

**Comment by muyiwafly** [comment]
Thank you, works great! So far no issues have appeared.
