### ISSUE TITLE
A shotcut to show the hint?

### ISSUE THREAD

**Issue by sandroden** [Liresol/anki-custom-shortcuts#74]
I use a lot hints as in ``<div class="hint">{{hint:context}}</div> ``, is it possible to add a shortcut to expand it? it's almost the only operation that force me to use the mouse! TIA

**Comment by thiswillbeyourgithub** [comment]
(By default i think it's G or H btw)

**Comment by sandroden** [comment]
> (By default i think it's G or H btw)

mmh, I don't think so. It doesn't work for me...

**Comment by thiswillbeyourgithub** [comment]
Try with all addons disabled, some addons interact with it. To dobso start anki with shift pressed

**Comment by sandroden** [comment]
I did, and neither G nor H work. Are you sure we're talking about the same situation? Is your shortcut documented somewhere? When using a hint I just see a link that when clicked displays some text. I guess it's using display css property...

**Comment by thiswillbeyourgithub** [comment]
My bad, I just checked and indeed I was wrong.

If I were you I would install the addon [hint hotkeys by glutanimate](https://ankiweb.net/shared/info/1844908621) and edit the code to use the shortcut I prefer

**Comment by sandroden** [comment]
Great, thanks! that's exactly what I wanted!
