### ISSUE TITLE
Custom Shortcuts

### ISSUE THREAD

**Issue by DoctorToBeIn23** [Liresol/anki-custom-shortcuts#83]
Can you get this add on to work with yours?
https://github.com/trgkanki/cloze_hide_all/issues/31#issuecomment-725998899

**Comment by Liresol** [comment]
Just pushed out an update for this.
The only thing you should have to do is update, but if there are any problems, let me know and I will look into it further.

**Comment by DoctorToBeIn23** [comment]
Eric thank you so much! I will take a look at it!

**Comment by DoctorToBeIn23** [comment]
It is working! 👍
