### ISSUE TITLE
Unable to use the M button as Reviewer choice 1 after update

### ISSUE THREAD

**Issue by tcc1** [Liresol/anki-custom-shortcuts#87]
After the update yesterday I am no longer able use the M button as my reviewer choice 1. I use N as reviewer choice 2 and space bar for good. These two buttons are still working. I have changed the reviewer options menu from M to another random button and this still has not fixed the issue. The M button still pulls up this reviewer menu and doesn't allow me to use M for option 1.

**Comment by Liresol** [comment]
Hello,
I was made aware of what I hope to be the bug that caused this earlier today, and there was a second update that should fix this issue.
However, if you are still having problems after the second update, I will look into it further.
Sorry for the inconvenience.

**Comment by tcc1** [comment]
i just did the update and it works now. Thanks!
