### ISSUE TITLE
shortcut conflict

### ISSUE THREAD

**Issue by DrewSSP** [Liresol/anki-custom-shortcuts#9]
Reassigning a shortcut, then using the default of that shortcut for another function results in the second shortcut not working.

For example, if a function has default shortcut A, reassigning it to have shortcut B will work properly. However, assigning another function with the shortcut A will then not work.

**Comment by DrewSSP** [comment]
Further details. This happened with the following config settings:

{
    "editor add media": "F3",
    "editor bold": "Ctrl+B",
    "editor card layout": "Ctrl+L",
    "editor change col": "F8",
    "editor cloze": "Ctrl+Shift+C",
    "editor cloze alt": "Ctrl+Shift+Alt+C",
    "editor focus tags": "Ctrl+Shift+T",
    "editor foreground": "F7",
    "editor html edit": "Ctrl+Shift+X",
    "editor insert latex": "Ctrl+T, T",
    "editor insert latex equation": "Ctrl+T, E",
    "editor insert latex math environment": "Ctrl+T, M",
    "editor insert mathjax block": "Ctrl+M, E",
    "editor insert mathjax chemistry": "Ctrl+M, C",
    "editor insert mathjax inline": "Ctrl+M, M",
    "editor italic": "Ctrl+I",
    "editor record sound": "F5",
    "editor remove format": "Ctrl+R",
    "editor subscript": "Ctrl+=",
    "editor superscript": "Ctrl++",
    "editor underline": "Ctrl+U",
    "m_toolbox addons": "Ctrl+Shift+A",
    "m_toolbox create filtered deck": "F",
    "m_toolbox export": "Ctrl+E",
    "m_toolbox import": "Ctrl+Shift+I",
    "m_toolbox preferences": "Ctrl+P",
    "m_toolbox quit": "Ctrl+Q",
    "m_toolbox see documentation": "F1",
    "m_toolbox study": "/",
    "m_toolbox switch profile": "Ctrl+Shift+P",
    "m_toolbox undo": "u",
    "main add": "a",
    "main browse": "b",
    "main debug": "Ctrl+:",
    "main deckbrowser": "d",
    "main stats": "t",
    "main study": "s",
    "main sync": "y",
    "reviewer _duplicates": {
        "reviewer choice 1": "i",
        "reviewer choice 2": "o",
        "reviewer choice 3": "p",
        "reviewer choice 4": "["
    },
    "reviewer bury card": "-",
    "reviewer bury note": "=",
    "reviewer choice 1": "1",
    "reviewer choice 2": "2",
    "reviewer choice 3": "3",
    "reviewer choice 4": "4",
    "reviewer delete note": "Ctrl+Delete",
    "reviewer edit current": "e",
    "reviewer flip card 1": " ",
    "reviewer flip card 2": "Qt.Key_Return",
    "reviewer flip card 3": "Qt.Key_Enter",
    "reviewer mark card": "*",
    "reviewer options menu": "o",
    "reviewer play recorded voice": "v",
    "reviewer record voice": "Shift+v",
    "reviewer replay audio 1": "r",
    "reviewer replay audio 2": "F5",
    "reviewer set flag 0": "Ctrl+0",
    "reviewer set flag 1": "Ctrl+1",
    "reviewer set flag 2": "Ctrl+2",
    "reviewer set flag 3": "Ctrl+3",
    "reviewer set flag 4": "Ctrl+4",
    "reviewer suspend card": "@",
    "reviewer suspend note": "!"
}

The issue happens with the shortcut "o".

**Comment by Liresol** [comment]
This is a known issue with the main shortcuts (and might not be fixable based on the way Anki itself is coded), but I think the add-on isn't working with "o" because the reviewer options menu is still (default) mapped to "o". If two shortcuts are mapped to the same key, neither one will work. 

Try mapping "reviewer options menu" to something like "Shift+O" and see if it works then. If not, I'll keep digging to see what I can find.

**Comment by DrewSSP** [comment]
Yup, that fixed it. I got so distracted by remapping undo that I must have forgotten to change the options shortcut when I reinstalled the app a few days ago. Sorry about that.

**Comment by Liresol** [comment]
No problem. Closing the issue now but might look into having duplicate detection.
