### ISSUE TITLE
Need shortcut for "editor: change note type"

### ISSUE THREAD

**Issue by gavinhughes** [Liresol/anki-custom-shortcuts#90]
Can a custom shortcut be created for `editor: change note type`?

**Comment by Liresol** [comment]
Hello,
There is a small chance that the shortcut you are looking for is already implemented (`window_browser change note type` might do what you want), though it's in the browser window.
The equivalent action in the editor window (which gets opened when you add a card) doesn't have a shortcut in Anki as far as I know, but I'll look to see if this can be made into a shortcut.

**Comment by gavinhughes** [comment]
Hi. I am familiar with the window_browser shortcut, but it's not the one.  I'm hoping for one on the add card dialog.

Thank you for looking into it.

**Comment by Liresol** [comment]
Sorry for the delay in getting around to this.
I just pushed out an update that adds `editor change note type` and should let you change the note type in the editor window. If it doesn't work, just let me know and I will look into it further.

**Comment by gavinhughes** [comment]
Very late reply, but thanks for adding this!
