### ISSUE TITLE
Spacebar Shortcut

### ISSUE THREAD

**Issue by pw3012** [Liresol/anki-custom-shortcuts#91]
How do I make a numeric shortcut for spacebar key on Anki? I have a numeric Bluetooth keyboard I want to use and would like to hit next card with the number 5 (or any other number).

**Comment by Liresol** [comment]
Hello,
It should be possible just to use `"5"` or any other number as a shortcut with that format, so something like `"reviewer flip card 3": "5"` should map the number 5 to flipping the card.

**Comment by pw3012** [comment]
That worked like a charm! I had another shortcut ("pause audio" defaulted as 5 so I just changed that to 8 since I prefer 5 to flip it). Thank you so much for the easy and effective solution--I appreciate it greatly!
