### ISSUE TITLE
Customizing "add card" shortcut from CTRL+Enter to something else

### ISSUE THREAD

**Issue by goathead111** [Liresol/anki-custom-shortcuts#94]
Hello, I am just wondering if it's possible to change the default shortcut of adding a card from CTRL+Enter to a different shortcut such as Alt+Enter. I tried looking at the config closely but couldn't find anything that would let me do that nor could I find any way to do that on Anki without the need of an addon. Any help is appreciated, thank you!

**Comment by Liresol** [comment]
Sorry for the delay, I had to get through the back half of school.
I have just pushed out an update that should let you change this with the name `editor confirm add card`, but let me know if this doesn't work or isn't what you want.

**Comment by goathead111** [comment]
> Sorry for the delay, I had to get through the back half of a school semester.
> I have just pushed out an update that should let you change this with the name `editor confirm add card`, but let me know if this doesn't work or isn't what you want.

Thank you so much! It works perfectly so far. I will let you know if I encounter any issues but it's working currently. 

And for anyone wondering, if the `editor confirm add card` doesn't show up after updating and restarting Anki, just delete the 'Customize Keyboard Shortcuts' addon, restart Anki, reinstall the addon with 24411424, restart Anki again, and it will show up in the config. 

Thanks again Liresol and happy holidays!
